services:
  mcpo:
    container_name: mcpo
    image: ghcr.io/open-webui/mcpo:main
    command: ["--api-key", "$API_KEY", "--config", "/app/data/config.json"]
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - MCP_CONFIG_PATH=/app/data/config.json
      - API_KEY=${API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
